version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "chore(deps):"
    groups:
      github-actions:
        patterns:
          - "*"
