{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pfsense-exporter.fullname" . }}
  labels:
    {{- include "pfsense-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pfsense-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.portName }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}