address: 0.0.0.0
port: 9945
targets:
  - host: "pfsense1.example.com"
    port: 443
    scheme: "https"
    auth_method: "basic"
    username: "admin"
    password: "pfsense"
    validate_cert: false
  - host: "pfsense2.example.com"
    port: 443
    scheme: "https"
    auth_method: "basic"
    username: "admin"
    password: "pfsense"
    validate_cert: false
    max_collector_concurrency: 5
    max_collector_buffer_size: 100
    collectors:
      - carp
