{
 "title": "pfSense Interfaces",
 "description": "Displays visuals for interface metrics.",
 "tags": [
  "pfsense",
  "pfrest",
  "networking"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pfsense_interface_up,host)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(pfsense_interface_up,descr)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface Status",
   "type": "stat",
   "description": "Displays the current status of interfaces.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_interface_up{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "{{ descr }} ({{ host }})"
    }
   ]
  },
  {
   "title": "Interface Pass Bytes",
   "type": "timeseries",
   "description": "Displays the count of bytes passed by a specific interface on the system. This includes both bytes received (in) and sent (out) by the interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "pfsense_interface_in_pass_bytes{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "In: {{ descr }} ({{ host }})"
    },
    {
     "expr": "pfsense_interface_out_pass_bytes{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "Out: {{ descr }} ({{ host }})"
    }
   ]
  },
  {
   "title": "Interface Pass Packets",
   "type": "timeseries",
   "description": "Displays the number of packets passed by a specific interface on the system. This includes both bytes received (in) and sent (out) by the interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "pfsense_interface_in_pass_pkts_count{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "In: {{ descr }} ({{ host }})"
    },
    {
     "expr": "pfsense_interface_out_pass_pkts_count{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "Out: {{ descr }} ({{ host }})"
    }
   ]
  },
  {
   "title": "Interface Bytes",
   "type": "timeseries",
   "description": "Displays the count of bytes seen by a specific interface on the system, regardless of whether the packet was passed or not. This includes both bytes received (in) and sent (out) by the interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "pfsense_interface_in_bytes{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "In: {{ descr }} ({{ host }})"
    },
    {
     "expr": "pfsense_interface_out_bytes{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "Out: {{ descr }} ({{ host }})"
    }
   ]
  },
  {
   "title": "Interface Packets",
   "type": "timeseries",
   "description": "Displays the number of packets seen by a specific interface on the system regardless of whether the packet was passed or not. This includes both bytes received (in) and sent (out) by the interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "pfsense_interface_in_pkts_count{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "In: {{ descr }} ({{ host }})"
    },
    {
     "expr": "pfsense_interface_out_pkts_count{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "Out: {{ descr }} ({{ host }})"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "timeseries",
   "description": "Displays the number of errors encountered by an interface. This includes both bytes received (in) and sent (out) by the interface.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "pfsense_interface_in_errs_count{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "In: {{ descr }} ({{ host }})"
    },
    {
     "expr": "pfsense_interface_out_errs_count{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "Out: {{ descr }} ({{ host }})"
    }
   ]
  },
  {
   "title": "Interface Collisions",
   "type": "timeseries",
   "description": "Displays the number of collisions encountered by an interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "pfsense_interface_collisions_count{job=~\"$job\", instance=~\"$instance\", host=~\"$host\", descr=~\"$interface\"}",
     "legendFormat": "{{ descr }} ({{ host }})"
    }
   ]
  }
 ]
}