{
 "title": "pfSense Gateways",
 "description": "Displays metrics relating to routing gateways on pfSense.",
 "tags": [
  "pfsense",
  "pfrest",
  "networking"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pfsense_gateway_up,host)"
    }
   },
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "label_values(pfsense_gateway_up,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway Status",
   "type": "gauge",
   "description": "Displays the current status of gateways.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pfsense_gateway_up{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", name=~\"$gateway\"}",
     "legendFormat": "{{name}} ({{ host }})"
    }
   ]
  },
  {
   "title": "Current Gateway Latency",
   "type": "gauge",
   "description": "Displays the current gateway latency in milliseconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_gateway_delay_seconds{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", name=~\"$gateway\"} * 1000",
     "legendFormat": "{{name}} ({{ host }})"
    }
   ]
  },
  {
   "title": "Current Gateway Jitter",
   "type": "gauge",
   "description": "Displays the current gateway jitter in milliseconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_gateway_stddev_seconds{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", name=~\"$gateway\"} * 1000",
     "legendFormat": "{{name}} ({{ host }})"
    }
   ]
  },
  {
   "title": "Gateway Latency",
   "type": "timeseries",
   "description": "Displays the latency (in seconds) of routing gateways over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pfsense_gateway_delay_seconds{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", name=~\"$gateway\"} * 1000",
     "legendFormat": "{{name}} ({{ host }})"
    }
   ]
  },
  {
   "title": "Gateway Jitter",
   "type": "timeseries",
   "description": "Displays the network jitter (standard deviation of latency) for pfSense gateways.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pfsense_gateway_stddev_seconds{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", name=~\"$gateway\"} * 1000",
     "legendFormat": "{{name}} ({{ host }})"
    }
   ]
  },
  {
   "title": "Gateway Loss",
   "type": "timeseries",
   "description": "Displays packet loss percentage of pfSense gateway.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pfsense_gateway_loss_ratio{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", name=~\"$gateway\"}",
     "legendFormat": "{{name}} ({{ host }})"
    }
   ]
  }
 ]
}