{
 "title": "pfSense CARP",
 "description": "Displays visualizations for CARP metrics.",
 "tags": [
  "pfsense",
  "pfrest",
  "networking"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pfsense_carp_enabled,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CARP Enabled",
   "type": "gauge",
   "description": "Indicates whether CARP is enabled or disabled on the pfSense host.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_carp_enabled{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Maintenance Mode",
   "type": "gauge",
   "description": "Indicates whether CARP maintenance mode is enabled or disabled.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_carp_maintenance_mode_enabled{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CARP Virtual IP Status",
   "type": "stat",
   "description": "Displays the current status of CARP virtual IPs.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_carp_virtual_ip_status{instance=~\"$instance\", job=~\"$job\", host=~\"$host\"}",
     "legendFormat": "{{ subnet }} ({{ host }})"
    }
   ]
  }
 ]
}