{
 "title": "pfSense DHCP",
 "description": "Displays visualizations for DHCP server metrics.",
 "tags": [
  "pfsense",
  "networking",
  "pfrest"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pfsense_dhcp_server_enabled{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pfsense_dhcp_pool_size, host)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(pfsense_dhcp_pool_size{host=~\"$host\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pool Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Utilization",
   "type": "gauge",
   "description": "Current DHCP pool utilization per interface. Green < 80%, yellow 80-90%, red > 90%.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_dhcp_pool_utilization{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Active Leases / Pool Size",
   "type": "stat",
   "description": "Active leases vs total pool capacity per interface.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_dhcp_leases_active{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} Active"
    },
    {
     "expr": "pfsense_dhcp_pool_size{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} Pool Size"
    }
   ]
  },
  {
   "title": "Pool Utilization Over Time",
   "type": "timeseries",
   "description": "DHCP pool utilization over time per interface.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pfsense_dhcp_pool_utilization{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  { "title": "Leases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Active Leases Over Time",
   "type": "timeseries",
   "description": "Active DHCP leases within the pool range over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pfsense_dhcp_leases_active{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Online Leases Over Time",
   "type": "timeseries",
   "description": "Online DHCP leases within the pool range over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pfsense_dhcp_leases_online{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  { "title": "Static Mappings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Static Mappings",
   "type": "stat",
   "description": "Total static mappings and how many are currently online per interface.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_dhcp_static_mappings_total{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} Total"
    },
    {
     "expr": "pfsense_dhcp_static_mappings_online{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{interface}} Online"
    }
   ]
  },
  {
   "title": "Static Mappings Online Over Time",
   "type": "timeseries",
   "description": "Online static mappings over time per interface.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "pfsense_dhcp_static_mappings_online{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "DHCP Server Status",
   "type": "stat",
   "description": "Whether the DHCP server is enabled for each interface.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfsense_dhcp_server_enabled{instance=~\"$instance\", job=~\"$job\", host=~\"$host\", interface=~\"$interface\"}",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  }
 ]
}